def getRemoveWord():
    remove_word = [
        'a',
        'an',
        'and',
        'any',
        'ago',
        'for',
        'in',
        'is',
        'it',
        'into',
        'here',
        'have',
        'had',
        'how',
        'of',
        'on',
        'your',
        'up',
        'or',
        'the',
        'there',
        'to',
        'you',
        'us',
        'this',
        'might',
        'meta',
        'el',
        'qt',
        'only',
        'how',
        'what',
        'where',
        'when',
        'with',
        'why',
        'that'
    ]

    return remove_word